# Generated by Django 6.1 on 2026-08-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='solutions_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Muammo yechimi (Xizmat)',
                'verbose_name_plural': 'Muammo yechimlari (Xizmatlar)',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Afzallik (Feature)',
                'verbose_name_plural': 'Afzalliklar (Features)',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('company', 'Kompaniya'), ('product', 'Mahsulot'), ('legal', 'Hujjatlar')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', max_length=255)),
            ],
            options={
                'verbose_name': 'Futering havolasi',
                'verbose_name_plural': 'Futer havolalari',
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_store_url', models.URLField(default='https://apple.com')),
                ('google_play_url', models.URLField(default='https://google.com')),
                ('copyright_text', models.CharField(default='© 2026 Copyright, All Right Reserved', max_length=255)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Futer sozlamasi',
                'verbose_name_plural': 'Futer sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Qanday ishlaydi qadami',
                'verbose_name_plural': 'Qanday ishlaydi qadamlari',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_period', models.CharField(default='/ mo', max_length=20)),
                ('team_members', models.CharField(max_length=100)),
                ('cloud_storage', models.CharField(max_length=100)),
                ('meetings', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tarif rejasi',
                'verbose_name_plural': 'Tarif rejalari',
            },
        ),
        migrations.CreateModel(
            name='TeamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('members_count', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Jamoa guruhi',
                'verbose_name_plural': 'Jamoa guruhlari',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='team_avatars/')),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "Jamoa a'olari",
            },
        ),
        migrations.CreateModel(
            name='TeamSectionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': "Jamoa bo'limi xususiyati",
                'verbose_name_plural': "Jamoa bo'limi xususiyatlari",
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_avatar', models.ImageField(upload_to='testimonials_avatars/')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz fikri',
                'verbose_name_plural': 'Mijozlar fikrlari',
            },
        ),
        migrations.CreateModel(
            name='VideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('cover_image', models.ImageField(upload_to='video_covers/')),
                ('video_url', models.URLField()),
            ],
            options={
                'verbose_name': "Video bo'limi",
                'verbose_name_plural': "Video bo'limlari",
            },
        ),
        migrations.AlterModelOptions(
            name='appdownload',
            options={'verbose_name': 'Ilova yuklash havolasi', 'verbose_name_plural': 'Ilova yuklash havolalari'},
        ),
        migrations.AlterModelOptions(
            name='birinchisahifa',
            options={'verbose_name': 'Bosh sahifa matni', 'verbose_name_plural': 'Bosh sahifa matnlari'},
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
    ]
